Sil\Bundle\CRMBundle\Entity\Organism:
    type: entity
    repositoryClass: Sil\Bundle\EmailCRMBundle\Entity\Repository\OrganismRepository

    manyToMany:
        emailMessages:
            targetEntity: Sil\Bundle\EmailBundle\Entity\Email
            mappedBy: organizations