Sil\Bundle\CRMBundle\Entity\Position:
    type: entity

    manyToMany:
        emailMessages:
            targetEntity: Sil\Bundle\EmailBundle\Entity\EmailInterface
            mappedBy: individuals
