Sil\Bundle\EmailBundle\Entity\Email:
    type: entity

    manyToMany:
        individuals:
            targetEntity: Sil\Bundle\CRMBundle\Entity\Position
            inversedBy: emailMessages
        organizations:
            targetEntity: Sil\Bundle\CRMBundle\Entity\Organism
            inversedBy: emailMessages
