services:
    librinfo_emailcrm.admin.organism:
        class: Librinfo\EmailCRMBundle\Admin\OrganismAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\Organism, LibrinfoCRMBundle:OrganismAdmin]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.organism_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [edit, LibrinfoCRMBundle:OrganismAdmin:edit.html.twig]]
            - [ setTemplate, [show, LibrinfoCRMBundle:OrganismAdmin:show.html.twig]]

    librinfo_emailcrm.admin.contact:
        class: Librinfo\EmailCRMBundle\Admin\ContactAdminConcrete
        arguments: [~, Librinfo\CRMBundle\Entity\Contact, LibrinfoCRMBundle:ContactAdmin]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.contact_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [edit, LibrinfoCRMBundle:ContactAdmin:edit.html.twig]]
            - [ setTemplate, [show, LibrinfoCRMBundle:ContactAdmin:show.html.twig]]
