parameters:
    blast:

############
# ORGANISM
############

        Sil\Bundle\CRMBundle\Admin\OrganismAdmin:
            Sonata\AdminBundle\Show\ShowMapper:
                remove:
                    email_history: ~
                add:
                    show_tab_emails:
                        '':
                            email_history:
                                template: SilEmailCRMBundle:CRUD:show_field_emails_list.html.twig
                                mapped: false
                    _options:
                        tabsOrder:
                            - show_tab_general
                            - show_tab_phones
                            - show_tab_addresses
                            - show_tab_individuals
                            - show_tab_info
                            - show_tab_emails
                            - form_group_specifics

#########
# EMAIL
#########

        # Sil\Bundle\EmailBundle\Admin\EmailAdmin:
        #     Sonata\AdminBundle\Form\FormMapper:
        #         add:
        #             form_group_general:
        #                 '':
        #                     organizations:
        #                         type: Blast\Bundle\BaseEntitiesBundle\Form\Type\SearchableAutocompleteType
        #                         serviceCallback: [sil_crm.admin.position, organizationsCallback, callback]
        #                         multiple: true
        #                         required: false
        #                         _options:
        #                             admin_code: sil_crm.admin.organism
        #                             btn_add: false
        #                     individuals:
        #                         type: Blast\Bundle\BaseEntitiesBundle\Form\Type\SearchableAutocompleteType
        #                         serviceCallback: [sil_crm.admin.position, individualsCallback, callback]
        #                         multiple: true
        #                         required: false
        #                         _options:
        #                             admin_code: sil_crm.admin.organism
        #                             btn_add: false
        #                     _options:
        #                         fieldsOrder:
        #                             - field_from
        #                             - field_to
        #                             - field_cc
        #                             - field_bcc
        #                             - organisms
        #                             - individuals
        #                             - field_subject
        #                             - template
        #                             - content
        #                             - attachments
        #     Sonata\AdminBundle\Datagrid\DatagridMapper:
        #         add:
        #             individuals:
        #                 type: doctrine_orm_model_autocomplete
        #                 admin_code: sil_crm.admin.organism
        #                 multiple: true
        #                 serviceCallback: [sil_crm.admin.position, individualsCallback, callback]
        #                 field_options:
        #                     class: "%sil_crm.entity.organism.class%"
        #                     property: label
        #                     admin_code: sil_email.admin.email
        #                     btn_add: false
        #             organizations:
        #                 type: doctrine_orm_model_autocomplete
        #                 admin_code: sil_crm.admin.organism
        #                 multiple: true
        #                 serviceCallback: [sil_crm.admin.position, organizationsCallback, callback]
        #                 field_options:
        #                     class: "%sil_crm.entity.organism.class%"
        #                     property: title
        #                     admin_code: sil_email.admin.email
        #                     btn_add: false
