services:
    sil_email.sender:
        class: Sil\Bundle\EmailCRMBundle\Services\Sender
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@sil_email.tracking'
            - '@sil_email.inline_attachments'
            - '@swiftmailer.mailer.direct_mailer'
            - '@swiftmailer.mailer.spool_mailer'
            - '@sil.email.address_manager'

    sil.email.address_manager:
        class: Sil\Bundle\EmailCRMBundle\Services\AddressManager

    sil_email_crm.replacements:
        class: Sil\Bundle\EmailCRMBundle\Services\SwiftMailer\DecoratorPlugin\Replacements
        arguments: [ '@doctrine.orm.entity_manager' ]

    swiftmailer.mailer.spool_mailer.spool.db:
        class: Sil\Bundle\EmailCRMBundle\Services\SwiftMailer\Spool\DbSpool
        arguments:
            - '@router'
            - '@doctrine.orm.entity_manager'
            - '%kernel.environment%'
            - '@sil.email.address_manager'
