services:

    blast_core.label.strategy.librinfo_emailcrm:
        class: Blast\Bundle\CoreBundle\Translator\LibrinfoLabelTranslatorStrategy
        arguments: ['Sil\Bundle\EmailCRMBundle']

    librinfo_email.sender:
        class: Sil\Bundle\EmailCRMBundle\Services\Sender
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@librinfo_email.tracking'
            - '@librinfo_email.inline_attachments'
            - '@swiftmailer.mailer.direct_mailer'
            - '@swiftmailer.mailer.spool_mailer'
            - '@librinfo.email.address_manager'

    librinfo.email.address_manager:
        class: Sil\Bundle\EmailCRMBundle\Services\AddressManager

    librinfo_email_crm.replacements:
        class: Sil\Bundle\EmailCRMBundle\Services\SwiftMailer\DecoratorPlugin\Replacements
        arguments: [ '@doctrine.orm.entity_manager' ]

    swiftmailer.mailer.spool_mailer.spool.db:
        class: Sil\Bundle\EmailCRMBundle\Services\SwiftMailer\Spool\DbSpool
        arguments:
            - '@router'
            - '@doctrine.orm.entity_manager'
            - '%kernel.environment%'
            - '@librinfo.email.address_manager'
