services:
    sil_emailcrm.admin.organism:
        class: Sil\Bundle\EmailCRMBundle\Admin\OrganismAdmin
        arguments: [~, "%sil_crm.entity.organism.class%", SilCRMBundle:OrganismAdmin]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.email_crm.menu_label.organism
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setTemplate, [edit, SilCRMBundle:OrganismAdmin:edit.html.twig]]
            - [ setTemplate, [show, SilCRMBundle:OrganismAdmin:show.html.twig]]
